//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_PAYMENT_TRANSACTION
    {
        public int COMPANY_PAYMENT_TRANSACTION_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public bool IS_DELETE { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_DELETE { get; set; }
        public int COMPANY_PAYMENT_ID { get; set; }
        public decimal PAID { get; set; }
        public int CURRENCY_TYPE { get; set; }
        public decimal CURRENCY_VALUE { get; set; }
        public decimal CURRENCY_PAID { get; set; }
        public string BILL_NUMBER { get; set; }
        public int RESPONSIBLE_USER_ID { get; set; }
        public string PAYMENT_TYPE_CODE { get; set; }
    
        public virtual COMPANY_PAYMENT COMPANY_PAYMENT { get; set; }
    }
}
