//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCY
    {
        public CURRENCY()
        {
            this.MODULE = new HashSet<MODULE>();
        }
    
        public string CURRENCY_CODE { get; set; }
        public string SYSTEM_NAME { get; set; }
    
        public virtual ICollection<MODULE> MODULE { get; set; }
    }
}
