//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fishermanager_webEntities : DbContext
    {
        public fishermanager_webEntities()
            : base("name=fishermanager_webEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMPANY> COMPANY { get; set; }
        public DbSet<COMPANY_ACCOUNTING> COMPANY_ACCOUNTING { get; set; }
        public DbSet<COMPANY_PARAMETER> COMPANY_PARAMETER { get; set; }
        public DbSet<COMPANY_PAYMENT> COMPANY_PAYMENT { get; set; }
        public DbSet<COMPANY_PAYMENT_TRANSACTION> COMPANY_PAYMENT_TRANSACTION { get; set; }
        public DbSet<COMPANY_SUBSCRIPTION> COMPANY_SUBSCRIPTION { get; set; }
        public DbSet<CURRENCY> CURRENCY { get; set; }
        public DbSet<LANGUAGE> LANGUAGE { get; set; }
        public DbSet<LANGUAGE_RES> LANGUAGE_RES { get; set; }
        public DbSet<MENU> MENU { get; set; }
        public DbSet<MESSAGE> MESSAGE { get; set; }
        public DbSet<MESSAGE_SETTING> MESSAGE_SETTING { get; set; }
        public DbSet<MODULE> MODULE { get; set; }
        public DbSet<PACKAGE> PACKAGE { get; set; }
        public DbSet<PACKAGE_CALCULATION> PACKAGE_CALCULATION { get; set; }
        public DbSet<PARAMETER_TYPE> PARAMETER_TYPE { get; set; }
        public DbSet<ROLE> ROLE { get; set; }
        public DbSet<SUBSCRIPTION> SUBSCRIPTION { get; set; }
        public DbSet<SUBSCRIPTION_MODULE> SUBSCRIPTION_MODULE { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USER_ACCOUNT> USER_ACCOUNT { get; set; }
    }
}
