//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.MENU1 = new HashSet<MENU>();
        }
    
        public int MENU_ID { get; set; }
        public Nullable<int> PARENT_MENU_ID { get; set; }
        public string NAME { get; set; }
        public string LANGUAGE_CODE { get; set; }
        public string SEO_URL { get; set; }
        public bool ACTIVE { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string ACTION_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public bool SHOW_ON_HEADER_MENU { get; set; }
        public bool SHOW_ON_FOOTER_MENU { get; set; }
        public int DISPLAY_ORDER { get; set; }
    
        public virtual LANGUAGE LANGUAGE { get; set; }
        public virtual ICollection<MENU> MENU1 { get; set; }
        public virtual MENU MENU2 { get; set; }
    }
}
