//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_SETTING
    {
        public string MESSAGE_SETTING_KEY { get; set; }
        public string MESSAGE_SETTING_VALUE { get; set; }
        public string HOST { get; set; }
        public Nullable<int> PORT { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> ENABLE_SSL { get; set; }
        public string DETAIL { get; set; }
    }
}
