//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public int MESSAGE_ID { get; set; }
        public string SUBJECT { get; set; }
        public string FARM_TYPE { get; set; }
        public string FARM_CAPACITY { get; set; }
        public string NUMBER_OF_EMPLOYEE { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string COMPANY_NAME { get; set; }
        public string MESSAGE_TEXT { get; set; }
        public string E_MAIL { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<System.DateTime> APPOINTMENT_TIME { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
    }
}
