//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULE
    {
        public MODULE()
        {
            this.SUBSCRIPTION_MODULE = new HashSet<SUBSCRIPTION_MODULE>();
        }
    
        public int MODULE_ID { get; set; }
        public string SYSTEM_CODE_NAME { get; set; }
        public string SYSTEM_CODE_DESCRIPTION { get; set; }
        public decimal PRICE_ADDITIONAL { get; set; }
        public bool IS_ACTIVE { get; set; }
        public bool IS_DELETE { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_DELETE { get; set; }
        public string CURRENCY_CODE { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual ICollection<SUBSCRIPTION_MODULE> SUBSCRIPTION_MODULE { get; set; }
    }
}
