//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKAGE_CALCULATION
    {
        public int PACKAGE_CALCULATION_ID { get; set; }
        public string PACKAGE_CODE { get; set; }
        public Nullable<decimal> PRICE_PER_MONTH { get; set; }
        public Nullable<int> CURRENCY_CODE { get; set; }
        public Nullable<decimal> ADDITIONAL_PRICE_PER_POOL { get; set; }
        public Nullable<decimal> ADDITIONAL_PRICE_PER_CAPACITY { get; set; }
        public Nullable<decimal> ADDITIONAL_PRICE_PER_USER { get; set; }
    
        public virtual PACKAGE PACKAGE { get; set; }
    }
}
