//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETER_TYPE
    {
        public PARAMETER_TYPE()
        {
            this.COMPANY_PARAMETER = new HashSet<COMPANY_PARAMETER>();
        }
    
        public string PARAMETER_TYPE_CODE { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string DESCRIPTION_CODE { get; set; }
        public string NAME { get; set; }
        public string INPUT_TYPE { get; set; }
    
        public virtual ICollection<COMPANY_PARAMETER> COMPANY_PARAMETER { get; set; }
    }
}
