//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisherManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIPTION
    {
        public SUBSCRIPTION()
        {
            this.COMPANY_SUBSCRIPTION = new HashSet<COMPANY_SUBSCRIPTION>();
            this.SUBSCRIPTION_MODULE = new HashSet<SUBSCRIPTION_MODULE>();
        }
    
        public int SUBSCRIPTION_ID { get; set; }
        public string SYSTEM_CODE_NAME { get; set; }
        public int PERIOD { get; set; }
        public decimal PRICE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public bool IS_DELETE { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_DELETE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string SYSTEM_CODE_DESCRIPTION { get; set; }
    
        public virtual ICollection<COMPANY_SUBSCRIPTION> COMPANY_SUBSCRIPTION { get; set; }
        public virtual ICollection<SUBSCRIPTION_MODULE> SUBSCRIPTION_MODULE { get; set; }
    }
}
